### ISSUE TITLE
Issue on running espresso.py

### ISSUE THREAD

**Issue by dellon80** [underspecified/web-ka#3]
Hi, my name is Christian. I'm a student of Sekolah Tinggi Teknik Surabaya University in Indonesia. We're currently doing a research about relation extraction using bootstrapping algorithm. We've tried your espresso, but we couldn't run it well. Our plan is implementing this tools for Bahasa Indonesia. Can I ask you how to run espresso.py for our implementation?

Best regards,
Christian NP

-----------------------------------------------------------------------------------------------------------------------------------
bootstrap_ex.sh: 13: bootstrap_ex.sh: source: not found
bootstrap_ex.sh: 15: bootstrap_ex.sh: function: not found
.
.
.
2017-08-23 08:26:55,539 [INFO/Espresso:promotes] initializing mongodb connection: done
max_pmi:Traceback (most recent call last):
  File "/home/admin_ps/data/Web-ka/tools/espresso.py", line 128, in <module>
    main()
  File "/home/admin_ps/data/Web-ka/tools/espresso.py", line 124, in main
    options.start)
  File "/home/admin_ps/data/Web-ka/tools/espresso.py", line 87, in __init__
    seeds, n, keep, reset, scorer, it
  File "/home/admin_ps/data/Web-ka/tools/bootstrapper.py", line 28, in __init__
    self.init_connection()
  File "/home/admin_ps/data/Web-ka/tools/bootstrapper.py", line 53, in init_connection
    self.db, self.matrix, self.boot_i, self.boot_p, self.logger
  File "/home/admin_ps/data/Web-ka/tools/scorers.py", line 90, in __init__
    self.max_pmi = self.pmi.max_pmi()
  File "/home/admin_ps/data/Web-ka/tools/matrix2pmi.py", line 270, in max_pmi
    print >>sys.stderr, 'max_pmi:', r['value']
TypeError: 'NoneType' object has no attribute '__getitem__'
bootstrap_ex.sh: 30: bootstrap_ex.sh: Syntax error: "}" unexpected

**Comment by underspecified** [comment]
Greetings,

You need to run the shell scripts (all files ending in '.sh') with the Bourne shell. Running them with sh will produce the errors you are encountering.

-underspecified
